Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/SOM_PEConfiguration__c.object-meta.xml
<CustomObject>
    <label>SOM Process Exception Configuration</label>
    <nameField>
        <label>SOM Process Exception Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOM Process Exception Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ConfigurationType__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationType__c</fullName>
    <label>Configuration Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>CustomNotification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/EmailSubject__c.field-meta.xml
<CustomField>
    <fullName>EmailSubject__c</fullName>
    <label>Email Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/Recipients__c.field-meta.xml
<CustomField>
    <fullName>Recipients__c</fullName>
    <description>Comma separated list of user recipients</description>
    <label>Recipients</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/SalesChannelId__c.field-meta.xml
<CustomField>
    <fullName>SalesChannelId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Channel</label>
    <referenceTo>SalesChannel</referenceTo>
    <relationshipLabel>SOM Process Exception Configurations</relationshipLabel>
    <relationshipName>SOM_Process_Exception_Configurations1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

salesforce-order-management-template/som-components/process-exception-notification/default/classes/SOM_EmailNotificationHandlerTest.cls
/** 
 * @description  : SOM_EmailNotificationHandler Test class
*/
@isTest
private class SOM_EmailNotificationHandlerTest {
    /**
    * @description Tests sendNotificationEmailToUsers method of SOM_EmailNotificationHandler class
    */
    @isTest
    static void shouldSendNotificationEmailToUsers() {
        String userId = UserInfo.getUserId();
        List<String> recipientList = new List<String>();            
        recipientList.add(userId);

        SOM_TestDataInput.SalesChannelInput salesChannelInput = new SOM_TestDataInput.SalesChannelInput();
        salesChannelInput.name = 'TestSalesChannel';
        SalesChannel salesChannel = SOM_TestDataFactory.createSalesChannel(salesChannelInput);
        insert salesChannel;

        SOM_PEConfiguration__c notificationConfiguration = new SOM_PEConfiguration__c(SalesChannelId__c = salesChannel.Id, Name = 'TestConfiguration', EmailSubject__c = 'EmailSubject', EmailBody__c = 'EmailBody', ConfigurationType__c = 'Email', Recipients__c = String.join(recipientList, ', '));
        insert notificationConfiguration;

        SOM_EmailNotificationHandler.EmailConfigurationWrapper wrapper = new SOM_EmailNotificationHandler.EmailConfigurationWrapper();
        wrapper.idsOfRecipientUsers = recipientList;
        wrapper.notificationConfiguration = notificationConfiguration;
        
        Test.startTest();
        SOM_EmailNotificationHandler.sendNotificationEmailToUsers(new List<SOM_EmailNotificationHandler.EmailConfigurationWrapper>{wrapper});
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();

        // Assert emails have been sent
        System.assertEquals(1, invocations,  'An email should be sent');
    }
}