Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/SOM_PEConfiguration__c.object-meta.xml
<CustomObject>
    <label>SOM Process Exception Configuration</label>
    <nameField>
        <label>SOM Process Exception Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOM Process Exception Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ChatterMessage__c.field-meta.xml
<CustomField>
    <fullName>ChatterMessage__c</fullName>
    <label>Chatter Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-order-management-template/som-components/process-exception-notification/default/classes/SOM_ChatterNotificationHandler.cls
/** 
 * @description  : Chatter Notification Handler class
*/
public with sharing class SOM_ChatterNotificationHandler {
    /**  
    * @description  : Wrapper method which includes list of user ids and one notification configuration
    */
    public class ChatterConfigurationWrapper{
        /**
         * @description idsOfRecipientUsers List of recipient ids
        */
        @InvocableVariable
        public List<String> idsOfRecipientUsers;
        /**
         * @description notificationConfiguration Notification configuration
        */
        @InvocableVariable
        public SOM_PEConfiguration__c notificationConfiguration;
    }
    /**  
    *   @description  : Adds mentioned users to chatter message
    *   @param chatterConfigurations wrapper which includes notification configurations and recipient list
    *   @return chatterMessage with mentioned users
    */
    @InvocableMethod(label='Get Chatter message with mentioned users')
    public static List<String> getChatterMessageWithMentions(List<SOM_ChatterNotificationHandler.ChatterConfigurationWrapper> chatterConfigurations) {
        List<String> chatterMessagesList = new List<String>();
        for (SOM_ChatterNotificationHandler.ChatterConfigurationWrapper wrapper : chatterConfigurations) {
            if (wrapper.idsOfRecipientUsers != null) {
                Integer numberOfRecipientsInConfigurations = wrapper.idsOfRecipientUsers.size();
                Integer numberOfMentions = numberOfRecipientsInConfigurations < 25 ? numberOfRecipientsInConfigurations : 25;
                String chatterMessage = wrapper.notificationConfiguration.ChatterMessage__c + ' ';
                for (Integer i = 0; i < numberOfMentions; i++) {
                    chatterMessage += '@[' + wrapper.idsOfRecipientUsers[i] + ']';
                }
                chatterMessagesList.add(chatterMessage);
            }
        }
        
        return chatterMessagesList;
    }
}