Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/SOM_PEConfiguration__c.object-meta.xml
<CustomObject>
    <label>SOM Process Exception Configuration</label>
    <nameField>
        <label>SOM Process Exception Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOM Process Exception Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ChatterMessage__c.field-meta.xml
<CustomField>
    <fullName>ChatterMessage__c</fullName>
    <label>Chatter Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ConfigurationType__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationType__c</fullName>
    <label>Configuration Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>CustomNotification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/CustomNotificationMessage__c.field-meta.xml
<CustomField>
    <fullName>CustomNotificationMessage__c</fullName>
    <label>Custom Notification Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/CustomNotificationTitle__c.field-meta.xml
<CustomField>
    <fullName>CustomNotificationTitle__c</fullName>
    <label>Custom Notification Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/CustomNotificationTypeId__c.field-meta.xml
<CustomField>
    <fullName>CustomNotificationTypeId__c</fullName>
    <label>Custom Notification Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/EmailSubject__c.field-meta.xml
<CustomField>
    <fullName>EmailSubject__c</fullName>
    <label>Email Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/IsPostToRelatedRecordFeedEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsPostToRelatedRecordFeedEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Post to Related Record Feed</label>
    <type>Checkbox</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ProcessExceptionCategories__c.field-meta.xml
<CustomField>
    <fullName>ProcessExceptionCategories__c</fullName>
    <description>Comma separated list of categories</description>
    <label>Process Exception Categories</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ProcessExceptionSeverities__c.field-meta.xml
<CustomField>
    <fullName>ProcessExceptionSeverities__c</fullName>
    <description>Comma separated list of severities</description>
    <label>Process Exception Severities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ProcessExceptionStatuses__c.field-meta.xml
<CustomField>
    <fullName>ProcessExceptionStatuses__c</fullName>
    <description>Comma separated list of statuses</description>
    <label>Process Exception Statuses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/Recipients__c.field-meta.xml
<CustomField>
    <fullName>Recipients__c</fullName>
    <description>Comma separated list of user recipients</description>
    <label>Recipients</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/SalesChannelId__c.field-meta.xml
<CustomField>
    <fullName>SalesChannelId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Channel</label>
    <referenceTo>SalesChannel</referenceTo>
    <relationshipLabel>SOM Process Exception Configurations</relationshipLabel>
    <relationshipName>SOM_Process_Exception_Configurations1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

salesforce-order-management-template/som-components/process-exception-notification/default/classes/SOM_ExceptionNotificationHelper.cls
/** 
 * @description  : Helper class of chatter, email and custom notification lighning web components
*/
public with sharing class SOM_ExceptionNotificationHelper {

    private static List<List<String>> recipientUsersListOfEachConfiguration = new List<List<String>>();
    private static List<List<String>> recipientGroupsListOfEachConfiguration = new List<List<String>>();
    private static List<List<String>> recipientRolesListOfEachConfiguration = new List<List<String>>();
    /**
    * @description gets Sales Channel Records
    * @return SalesChannelRecords
    */
    @AuraEnabled(cacheable=true)
    public static List<SalesChannel> getSalesChannelList(){
        try {
            return [SELECT Id, SalesChannelName FROM SalesChannel WITH SECURITY_ENFORCED];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /**
    * @description gets process exception configurations by configuration type and sales channel id
    * @param configuratonType configuration type
    * @param salesChannelId sales channel Id
    * @return List of ProcessExceptionConfigurations
    */
    @AuraEnabled(cacheable=true)
    public static List<SOM_PEConfiguration__c> selectProcessExceptionConfigurationByConfigurationTypeAndSalesChannel(String configuratonType, String salesChannelId) {
        try {
            return [SELECT  
                        Name,
                        ChatterMessage__c,
                        IsPostToRelatedRecordFeedEnabled__c,
                        ConfigurationType__c,
                        CustomNotificationMessage__c,
                        CustomNotificationTitle__c,
                        CustomNotificationTypeId__c,
                        EmailBody__c,
                        EmailSubject__c,
                        ProcessExceptionCategories__c,
                        ProcessExceptionSeverities__c,
                        ProcessExceptionStatuses__c,
                        Recipients__c
                    FROM SOM_PEConfiguration__c 
                    WHERE ConfigurationType__c =: configuratonType AND SalesChannelId__c =: salesChannelId
                    WITH SECURITY_ENFORCED];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /**
    * @description gets Custom Notification Type records
    * @return list of Custom Notification Type Records
    */
    @AuraEnabled(cacheable=true)
    public static List<CustomNotificationType> getCustomNotificationTypeList(){
        if (Test.isRunningTest()) {
            CustomNotificationType testCustomNotificationType = new CustomNotificationType(CustomNotifTypeName = 'Testing Notification Type');
            return new List<CustomNotificationType>{testCustomNotificationType};
        }
        try {
            return [SELECT Id, CustomNotifTypeName FROM CustomNotificationType WITH SECURITY_ENFORCED];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    *   @description gets user Ids from recipientIds field of SOM_PEConfiguration__c object
    *   @param notificationConfigurations wrapper which includes notification configurations and recipient list
    *   @return list of user ids
    */
    @InvocableMethod(label='Get Ids of users in recipient list')
    public static List<List<String>> getIdsOfUsersInRecipientList(List<SOM_PEConfiguration__c> notificationConfigurations) {
        List<String> recipientGroupsOfAllConfigurations = new List<String>();
        List<String> recipientRolesOfAllConfigurations = new List<String>();
        for (SOM_PEConfiguration__c currentConfiguration : notificationConfigurations) {
            List<String> recipientIdList = currentConfiguration.Recipients__c.split(',');
            // Get Ids to be mentioned in chatter post
            List<String> idsOfRecipientUsers = new List<String>();
            List<String> roleRecipientIds = new List<String>();
            List<String> groupRecipientIds = new List<String>();
            for (String recipientId : recipientIdList) {
                if(Id.valueOf(recipientId).getSObjectType() == User.getSObjectType()){
                    idsOfRecipientUsers.add(recipientId);
                }else if(Id.valueOf(recipientId).getSObjectType() == Group.getSObjectType()){
                    groupRecipientIds.add(recipientId);
                }else if(Id.valueOf(recipientId).getSObjectType() == UserRole.getSObjectType()){
                    roleRecipientIds.add(recipientId);
                }
            }
            recipientRolesOfAllConfigurations.addAll(roleRecipientIds);
            recipientGroupsOfAllConfigurations.addAll(groupRecipientIds);

            recipientUsersListOfEachConfiguration.add(idsOfRecipientUsers);
            recipientGroupsListOfEachConfiguration.add(groupRecipientIds);
            recipientRolesListOfEachConfiguration.add(roleRecipientIds);
        }
        List<GroupMember> membersOfRecipientGroups = [SELECT GroupId, UserOrGroupId FROM GroupMember WHERE GroupId IN: recipientGroupsOfAllConfigurations WITH SECURITY_ENFORCED];
        List<User> usersOfRecipientRoles = [SELECT Id, UserRoleId FROM User WHERE UserRoleId IN: recipientRolesOfAllConfigurations WITH SECURITY_ENFORCED];
        return getUserIdsFromDifferentRecipientTypes(notificationConfigurations, membersOfRecipientGroups, usersOfRecipientRoles);
    }
    
    /**
    *   @description gets user Ids from different recipient types | Helper method
    *   @param notificationConfigurations wrapper which includes notification configurations and recipient list
    *   @param membersOfRecipientGroups list of members of recipient groups
    *   @param usersOfRecipientRoles list of users which have one of recipient roles
    *   @return recipientIds  | List<List<String>>
    */
    public static List<List<String>> getUserIdsFromDifferentRecipientTypes(List<SOM_PEConfiguration__c> notificationConfigurations, List<GroupMember> membersOfRecipientGroups,  List<User> usersOfRecipientRoles) {
        List<List<String>> recipientIds = new List<List<String>>();
        for (Integer configurationIndex = 0; configurationIndex < notificationConfigurations.size(); configurationIndex++) {
            List<String> recipientsOfCurrentConfiguration = new List<String>();
            recipientsOfCurrentConfiguration.addAll(recipientUsersListOfEachConfiguration[configurationIndex]);
            // Check if groupMember's groupId in recipient list of configuration
            for (GroupMember groupMember : membersOfRecipientGroups) {
                if (recipientGroupsListOfEachConfiguration[configurationIndex].contains(groupMember.GroupId) && Id.valueOf(groupMember.UserOrGroupId).getSObjectType() == User.getSObjectType()) {
                        recipientsOfCurrentConfiguration.add(groupMember.UserOrGroupId);
                }
            }
            // Check if user's role in recipient list of configuration
            for (User userWithSpecifiedRole : usersOfRecipientRoles) {
                if (recipientRolesListOfEachConfiguration[configurationIndex].contains(userWithSpecifiedRole.UserRoleId)) {
                    recipientsOfCurrentConfiguration.add(userWithSpecifiedRole.Id);
                }
            }
            recipientIds.add(recipientsOfCurrentConfiguration);
        }
        return recipientIds;
    }
}