Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/SOM_PEConfiguration__c.object-meta.xml
<CustomObject>
    <label>SOM Process Exception Configuration</label>
    <nameField>
        <label>SOM Process Exception Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOM Process Exception Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ChatterMessage__c.field-meta.xml
<CustomField>
    <fullName>ChatterMessage__c</fullName>
    <label>Chatter Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ConfigurationType__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationType__c</fullName>
    <label>Configuration Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>CustomNotification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/Recipients__c.field-meta.xml
<CustomField>
    <fullName>Recipients__c</fullName>
    <description>Comma separated list of user recipients</description>
    <label>Recipients</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/SalesChannelId__c.field-meta.xml
<CustomField>
    <fullName>SalesChannelId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Channel</label>
    <referenceTo>SalesChannel</referenceTo>
    <relationshipLabel>SOM Process Exception Configurations</relationshipLabel>
    <relationshipName>SOM_Process_Exception_Configurations1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/classes/SOM_ChatterNotificationHandlerTest.cls
/** 
 * @description  : SOM_ChatterNotificationHandler Test Class
*/
@isTest
private with sharing class SOM_ChatterNotificationHandlerTest {
    /**
    * @description Tests getChatterMessageWithMentions method of SOM_ChatterNotificationHandler class
    */
    @isTest
    static void shouldGetChatterMessageWithMentions() {
        String userId = UserInfo.getUserId();
        List<String> recipientList = new List<String>();
        for (Integer i = 0; i < 30; i++) {
            recipientList.add(userId);
        }
        SOM_TestDataInput.SalesChannelInput salesChannelInput = new SOM_TestDataInput.SalesChannelInput();
        salesChannelInput.name = 'TestSalesChannel';
        SalesChannel salesChannel = SOM_TestDataFactory.createSalesChannel(salesChannelInput);
        insert salesChannel;

        SOM_PEConfiguration__c notificationConfiguration = new SOM_PEConfiguration__c(SalesChannelId__c = salesChannel.Id, Name = 'TestConfiguration', ChatterMessage__c = 'Test:', ConfigurationType__c = 'Chatter', Recipients__c = String.join(recipientList, ', '));
        insert notificationConfiguration;

        SOM_ChatterNotificationHandler.ChatterConfigurationWrapper wrapper = new SOM_ChatterNotificationHandler.ChatterConfigurationWrapper();
        wrapper.idsOfRecipientUsers = recipientList;
        wrapper.notificationConfiguration = notificationConfiguration;
        Test.startTest();
        String chatterMessage = SOM_ChatterNotificationHandler.getChatterMessageWithMentions(new List<SOM_ChatterNotificationHandler.ChatterConfigurationWrapper>{wrapper})[0];
        Test.stopTest();

        String expectedMessage = 'Test: ';
        for (Integer i = 0; i < 25; i++) {
            expectedMessage += '@['+ userId +']';
        }
        system.assertEquals(expectedMessage, chatterMessage, 'Unexpected chatter message');
    }
}