Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/SOM_PEConfiguration__c.object-meta.xml
<CustomObject>
    <label>SOM Process Exception Configuration</label>
    <nameField>
        <label>SOM Process Exception Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOM Process Exception Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ChatterMessage__c.field-meta.xml
<CustomField>
    <fullName>ChatterMessage__c</fullName>
    <label>Chatter Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/ConfigurationType__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationType__c</fullName>
    <label>Configuration Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>CustomNotification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/EmailSubject__c.field-meta.xml
<CustomField>
    <fullName>EmailSubject__c</fullName>
    <label>Email Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/IsPostToRelatedRecordFeedEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsPostToRelatedRecordFeedEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Post to Related Record Feed</label>
    <type>Checkbox</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/Recipients__c.field-meta.xml
<CustomField>
    <fullName>Recipients__c</fullName>
    <description>Comma separated list of user recipients</description>
    <label>Recipients</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/objects/SOM_PEConfiguration__c/fields/SalesChannelId__c.field-meta.xml
<CustomField>
    <fullName>SalesChannelId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Channel</label>
    <referenceTo>SalesChannel</referenceTo>
    <relationshipLabel>SOM Process Exception Configurations</relationshipLabel>
    <relationshipName>SOM_Process_Exception_Configurations1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/process-exception-notification/default/classes/SOM_ExceptionNotificationHelperTest.cls
/** 
 * @description  : SOM_ExceptionNotificationHelper Test class
*/
@isTest
private class SOM_ExceptionNotificationHelperTest {
    /**
    * @description Tests getSalesChannelList method of SOM_ExceptionNotificationHelper class
    */
    @isTest
    static void shouldGetSalesChannelList() {
        SalesChannel testSalesChannel = new SalesChannel(SalesChannelName='testChannel');
        insert testSalesChannel;
        Test.startTest();
        List<SalesChannel> selectedSalesChannels = SOM_ExceptionNotificationHelper.getSalesChannelList();
        Test.stopTest();
        
        System.assert(!selectedSalesChannels.isEmpty(), 'No Sales Channel record(s) found');
    }

    /**
    * @description Tests selectProcessExceptionConfigurationByConfigurationTypeAndSalesChannel method of SOM_ExceptionNotificationHelper class
    */
    @isTest
    static void shouldSelectProcessExceptionConfigurationByConfigurationTypeAndSalesChannel() {
        SalesChannel testSalesChannel = new SalesChannel(SalesChannelName='testChannel');
        String salesChannelId = Database.insert(new List<SalesChannel>{testSalesChannel})[0].Id;

        SOM_PEConfiguration__c testConfiguration = new SOM_PEConfiguration__c(
            Name = 'testConfiguration',
            ChatterMessage__c = 'testMessage',
            IsPostToRelatedRecordFeedEnabled__c = true,
            ConfigurationType__c = 'Chatter',
            Recipients__c = String.valueOf(salesChannelId),
            SalesChannelId__c = salesChannelId);
        insert testConfiguration;
        
        Test.startTest();
        List<SOM_PEConfiguration__c> processExceptionConfigurations = SOM_ExceptionNotificationHelper.selectProcessExceptionConfigurationByConfigurationTypeAndSalesChannel('Chatter', salesChannelId);
        Test.stopTest();
        
        System.assert(!processExceptionConfigurations.isEmpty(), 'No Process Exception Configuration record(s) found');
    }

    /**
    * @description Tests getCustomNotificationTypeList method of SOM_ExceptionNotificationHelper class
    */
    @isTest
    static void shouldGetCustomNotificationTypeList() {
        Test.startTest();
        List<CustomNotificationType> customNotificationTypes = SOM_ExceptionNotificationHelper.getCustomNotificationTypeList();
        Test.stopTest();

        System.assert(!customNotificationTypes.isEmpty(), 'No Custom Notification Type record(s) found');
    }

    /**
    * @description Tests getIdsOfUsersInRecipientList method of SOM_ExceptionNotificationHelper class
    */
    @isTest
    static void shouldGetIdsOfUsersInRecipientList() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Saleschannel salesChannel = new SalesChannel(SalesChannelName = 'TestSalesChannel');
        insert salesChannel;
        // Insert recipient users
        System.runAs (thisUser) {
            UserRole userRole = new UserRole(Name = 'Finance Approver');
            insert userRole;
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
            List<User> newUsersList = new List<User>();
            newUsersList.add(
                new User(alias = 'jsmith', email='jsmith@acme.com', 
                emailencodingkey='UTF-8', lastname='Smith', 
                languagelocalekey='en_US', 
                localesidkey='en_US', profileid = p.Id, userroleid = userRole.Id,
                timezonesidkey='America/Los_Angeles', 
                username='testUserName1@acme.com')
            );
            newUsersList.add(
                new User(alias = 'jsmith', email='jsmith@acme.com', 
                emailencodingkey='UTF-8', lastname='Smith', 
                languagelocalekey='en_US', 
                localesidkey='en_US', profileid = p.Id, userroleid = userRole.Id,
                timezonesidkey='America/Los_Angeles', 
                username='testUserName2@acme.com')
            );
            newUsersList.add(
                new User(alias = 'jsmith', email='jsmith@acme.com', 
                emailencodingkey='UTF-8', lastname='Smith', 
                languagelocalekey='en_US', 
                localesidkey='en_US', profileid = p.Id, userroleid = userRole.Id,
                timezonesidkey='America/Los_Angeles', 
                username='testUserName3@acme.com')
            );
            List<Database.SaveResult> insertionResults = Database.insert(newUsersList);
            Account account = new Account(name='Acme');
            insert account;
            // Create new group and add user to public group
            Group testGroup = new Group();
            testGroup.Name = 'Test Group';
            insert testGroup;
            GroupMember groupMember = new GroupMember();
            groupMember.GroupId = testGroup.Id;
            groupMember.UserOrGroupId = insertionResults[2].Id;
            insert groupMember;
            SOM_PEConfiguration__c notificationConfiguration = new SOM_PEConfiguration__c(SalesChannelId__c = salesChannel.Id, Name = 'TestConfiguration', EmailSubject__c = 'EmailSubject', EmailBody__c = 'EmailBody', ConfigurationType__c = 'Email', Recipients__c = userRole.Id + ',' + insertionResults[2].Id + ',' + testGroup.Id);
            insert notificationConfiguration;
            Test.startTest();
            List<String> userIds = SOM_ExceptionNotificationHelper.getIdsOfUsersInRecipientList(new List<SOM_PEConfiguration__c>{notificationConfiguration})[0];
            Test.stopTest();
            System.assert(userIds.contains(insertionResults[0].Id) && userIds.contains(insertionResults[1].Id) && userIds.contains(insertionResults[2].Id), 'No User Id found');
        }
    }

}