Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/objects/OrderSummary/fields/CancelAuthorizationRetryAttempts__c.field-meta.xml
<CustomField>
    <fullName>CancelAuthorizationRetryAttempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Authorization Cancellation Tries</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/objects/OrderSummary/fields/CancelAuthorizationStatus__c.field-meta.xml
<CustomField>
    <fullName>CancelAuthorizationStatus__c</fullName>
    <description>Status of the payment authorization cancellation</description>
    <label>Authorization Cancellation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RequestSent</fullName>
            </value>
            <value>
                <fullName>AuthorizationReleased</fullName>
            </value>
            <value>
                <fullName>RequestFailed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_Log__c/SOM_Log__c.object-meta.xml
<CustomObject>
    <label>OMS Log</label>
    <nameField>
        <displayFormat>Log-{0}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMS Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the log.</description>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message of the log.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/classes/batchJobs/retryCancelAuthorization/SOM_CancelAuthorizationsBatchTest.cls
/**
 * @description  Cancel payment authorization
 *       test class of batch job for CancelAuthorization retry
 */
@isTest
private with sharing class SOM_CancelAuthorizationsBatchTest {
    /**
     * @description test setup method for SOM_BaseCancelAuthorizationHandlerTest, SOM_AdyenAuthorizationCancelHandlerTest
     * @return Id of created order summary
     */
    private static Id makeData() {
        //prepare test data and update order summary status
        Map<String, String> testDataOptions = new Map<String, String>
        {
            SOM_TestDataInputOptions.CREATE_PAYMENT_GATEWAY => 'true'
        };
        
        String orderId = SOM_TestDataFactory.createOrderAction(testDataOptions);
        OrderSummary orderSummary = SOM_TestDataFactory.createOrderSummary(orderId);

        PaymentGateway gateway = [
            SELECT Id
            FROM PaymentGateway
            WHERE ExternalReference = :SOM_CancelPaymentAuthorizationConstants.TEST_PAYMENT_GATEWAY_EXTERNAL_REFERENCE
        ];
        SOM_TestDataFactory.createPaymentAuthHistory(orderId, orderSummary.Id, Double.valueOf(100), gateway.Id, false);

        orderSummary.Status = SOM_OrderSummaryStatus.CANCELLED.toString();
        orderSummary.CancelAuthorizationStatus__c = SOM_CancelPaymentAuthorizationConstants.AUTHORIZATION_CANCEL_REQUEST_FAILED;
        orderSummary.CancelAuthorizationRetryAttempts__c = 0;
        update orderSummary;

        Test.getEventBus().deliver();
        return orderSummary.Id;
    }

    /**
     * @description Tests the case when a retry event needs to be published
     */
    @isTest(SeeAllData=true)
    @suppressWarnings('PMD.ApexUnitTestShouldNotUseSeeAllDataTrue')
    static void shouldPublishEvent() {
        Id orderSummaryId = makeData();
        Test.setMock(HttpCalloutMock.class, new SOM_CancelPaymentAuthRestSuccessMock());

        OrderSummary orderSummary = [
            SELECT OrderNumber, Status, CancelAuthorizationStatus__c, CancelAuthorizationRetryAttempts__c
            FROM OrderSummary
            WHERE Id = :orderSummaryId
        ];

        orderSummary.CancelAuthorizationRetryAttempts__c = 4;
        update orderSummary;

        Test.startTest();
        SOM_CancelAuthorizationsBatch ba = new SOM_CancelAuthorizationsBatch('Cancel Authorization');
        ba.execute(null);

        Test.stopTest();
        String infoMessage =
            'Creating platform event record for sending cancel authorization request for order:' + orderSummaryId;
        SOM_Log__c logEntry = [
            SELECT Message__c
            FROM SOM_Log__c
            WHERE Category__c = 'Payment'
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        System.assertEquals(infoMessage, logEntry.Message__c, 'Platform event should be created');
    }

    /**
     * @description Tests the case when a retry event needs to be published
     */
    @isTest(SeeAllData=true)
    @suppressWarnings('PMD.ApexUnitTestShouldNotUseSeeAllDataTrue')
    static void shouldNotPublishEventMaxAttempts() {
        Id orderSummaryId = makeData();
        Test.setMock(HttpCalloutMock.class, new SOM_CancelPaymentAuthRestSuccessMock());

        OrderSummary orderSummary = [
            SELECT OrderNumber, Status, CancelAuthorizationStatus__c, CancelAuthorizationRetryAttempts__c
            FROM OrderSummary
            WHERE Id = :orderSummaryId
        ];

        orderSummary.CancelAuthorizationRetryAttempts__c = 5;
        update orderSummary;

        Test.startTest();
        SOM_CancelAuthorizationsBatch ba = new SOM_CancelAuthorizationsBatch('Cancel Authorization');
        ba.execute(null);

        Test.stopTest();
        List<SOM_Log__c> logEntry = [
                SELECT Message__c
                FROM SOM_Log__c
                WHERE Category__c = 'Payment'
                ORDER BY CreatedDate DESC
                LIMIT 1
            ];

        System.assertEquals(0, logEntry.size(), 'Platform event should not have been created');
    }
}