Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/objects/SOM_PaymentGatewayInfo__mdt/SOM_PaymentGatewayInfo__mdt.object-meta.xml
<CustomObject>
    <description>Information about each particular payment gateway</description>
    <label>Payment Gateway Info</label>
    <pluralLabel>Payment Gateways Info</pluralLabel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/objects/SOM_PaymentGatewayInfo__mdt/fields/CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>CalloutURL__c</fullName>
    <description>The Callout URL</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/objects/SOM_PaymentGatewayInfo__mdt/fields/GatewayName__c.field-meta.xml
<CustomField>
    <fullName>GatewayName__c</fullName>
    <description>The Payment Processor gateway label</description>
    <label>Gateway Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adyen</fullName>
                <default>true</default>
                <label>Adyen</label>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/classes/SOM_PaymentGatewayUtil.cls
/**
 * @description Cancel payment authorization utility
 *      class with methods related to payment gateways
 */
public with sharing class SOM_PaymentGatewayUtil {
    /**
     * @description retrieves the payment gateway information based on the name given
     *  or save error log if not found
     * @param paymentGatewayName String
     * @return SOM_PaymentGatewayInfo__mdt
     */
    public static SOM_PaymentGatewayInfo__mdt getPaymentGatewayInfo(String paymentGatewayName) {
        SOM_PaymentGatewayInfo__mdt data = Test.isRunningTest()
            ? createPaymentGatewayInfo()
            : SOM_PaymentGatewayInfo__mdt.getInstance(paymentGatewayName);

        if (Test.isRunningTest() && paymentGatewayName.equals('fail')) {
            data = null;
        }

        if (data != null) {
            return data;
        }

        SOM_LogUtil.createErrorLog(
            SOM_Constants.PAYMENT,
            String.format(
                '{0} {1} {2}',
                new List<String>{
                    SOM_CancelPaymentAuthorizationConstants.ERROR_FINDING_PAYMENT_GATEWAY_METADATA,
                    ' Payment Gateway Name: ',
                    paymentGatewayName
                }
            )
        );

        return null;
    }

    /**
     * @description Creates Batch Configuration metadata record
     * @return Batch Configuration metadata record
     */
    private static SOM_PaymentGatewayInfo__mdt createPaymentGatewayInfo() {
        SOM_PaymentGatewayInfo__mdt configuration = new SOM_PaymentGatewayInfo__mdt();
        configuration.CalloutURL__c = 'callout:Adyen_Notification';
        configuration.GatewayName__c = 'Adyen';
        
        return configuration;
    }
}