Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/objects/SOM_PaymentGatewayInfo__mdt/SOM_PaymentGatewayInfo__mdt.object-meta.xml
<CustomObject>
    <description>Information about each particular payment gateway</description>
    <label>Payment Gateway Info</label>
    <pluralLabel>Payment Gateways Info</pluralLabel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/objects/SOM_PaymentGatewayInfo__mdt/fields/CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>CalloutURL__c</fullName>
    <description>The Callout URL</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

salesforce-order-management-template/som-components/cancel-payment-authorization/main/default/classes/SOM_PaymentGatewayUtilTest.cls
/**
 *  @description Cancel payment authorization - SOM Payment Gateway Util test class
 */
@isTest
public with sharing class SOM_PaymentGatewayUtilTest {
    /**
     * @description SOM_PaymentGatewayUtil.getPaymentGatewayInfo positive test
     */
    @isTest
    static void shouldHandle() {
        // Then, use it in the getPaymentInfo method
        String uri = SOM_PaymentGatewayUtil.getPaymentGatewayInfo('test')?.CalloutURL__c;
        System.assert(uri != null, 'Callout URL should not be null');
    }

    /**
     * @description SOM_PaymentGatewayUtil.getPaymentGatewayInfo negative test
     */
    @isTest
    static void shouldFail() {
        // Then, use it in the getPaymentInfo method
        SOM_PaymentGatewayInfo__mdt paymentMdt = SOM_PaymentGatewayUtil.getPaymentGatewayInfo('fail');
        System.assert(paymentMdt == null, 'Metadata should be null');
    }
}