Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/SOM_FailedRequest__c.object-meta.xml
<CustomObject>
    <label>Failed Request</label>
    <nameField>
        <label>Failed Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Failed Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/RetryAttemptLimit__c.field-meta.xml
<CustomField>
    <fullName>RetryAttemptLimit__c</fullName>
    <defaultValue>3</defaultValue>
    <description>Indicates the limit for retry attempts.</description>
    <label>Retry Attempt Limit</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/RetryAttempts__c.field-meta.xml
<CustomField>
    <fullName>RetryAttempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the number of retry attempts.</description>
    <label>Retry Attempts</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-order-management-template/force-app/main/default/classes/selectors/failedRequest/SOM_FailedRequestSelectorTest.cls
/**
* @description FailedRequestSelector test class
*/
@isTest
private class SOM_FailedRequestSelectorTest {
    @isTest(SeeAllData=true)
    @suppressWarnings('PMD.ApexUnitTestShouldNotUseSeeAllDataTrue')
    static void shouldselectByAvaibilityOfRetryAndStatus() {
        SOM_FailedRequest__c failedRequest = new SOM_FailedRequest__c(Name='Test Request', RetryAttempts__c = 10, RetryAttemptLimit__c = 12);
        insert failedRequest;

        Test.startTest();
        List<SOM_FailedRequest__c> failedRequests = new SOM_FailedRequestSelector().selectByAvaibilityOfRetryAndStatus(false, 'NOT STARTED', 200);
        Test.stopTest();

        System.assert(!failedRequests.isEmpty(), 'No failed requests found');
    }
}