Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/SOM_FailedRequest__c.object-meta.xml
<CustomObject>
    <label>Failed Request</label>
    <nameField>
        <label>Failed Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Failed Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/RetryAttempts__c.field-meta.xml
<CustomField>
    <fullName>RetryAttempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the number of retry attempts.</description>
    <label>Retry Attempts</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the retry object.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT STARTED</fullName>
                <default>true</default>
                <label>NOT STARTED</label>
            </value>
            <value>
                <fullName>IN PROGRESS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/classes/batchJobs/retryFailedRequests/SOM_RetryFailedRequestsBatchHandler.cls
/**
 * @description Retry fail batch request handler
 */
public with sharing class SOM_RetryFailedRequestsBatchHandler {

    private List<SObject> allSObjectListToBeUpdated = new List<SObject>();
    private List<Id> allSObjectIdListToBeDeleted = new List<Id>();
    
    /**
    * @description get allSObjectListToBeUpdated
    * @return List of Sobjects
    */

    public List<SOM_FailedRequest__c> getAllSObjectListToBeUpdated() {
        return this.allSObjectListToBeUpdated;
    }

    /**
    * @description get allSObjectIdListToBeDeleted
    * @return List of Ids
    */

    public List<Id> getAllSObjectIdListToBeDeleted() {
        return this.allSObjectIdListToBeDeleted;
    }
    
    /**
    * @description updates status field of FailedRequests to "IN PROGRESS"
    * @param failedRequests List of FailedRequests
    */
    public void updateStatusToInProgress(List<SOM_FailedRequest__c> failedRequests) {
        List<SOM_FailedRequest__c> failedRequestInProgress = new List<SOM_FailedRequest__c>();
        
        for(SOM_FailedRequest__c failedRequest : failedRequests) {
            failedRequest.Status__c = 'IN PROGRESS';
            failedRequestInProgress.add(failedRequest);
        }
        
        SOM_DatabaseUtil.updateRecords(failedRequestInProgress, false);
        SOM_Application.commitChanges();
    }
    
    /**
    * @description Manages to invoke the handle
    * @param failedRequestRecordList List of FailedRequests
    */
    public void manage(List<SOM_FailedRequest__c> failedRequestRecordList) {
        for(SOM_FailedRequest__c failedRequest : failedRequestRecordList) {
            if(retryFailedRequest(failedRequest)) {
                this.allSObjectIdListToBeDeleted.add(failedRequest.Id);
            } else {
                failedRequest.Status__c = 'NOT STARTED';
                failedRequest.RetryAttempts__c +=1;
                this.allSObjectListToBeUpdated.add(failedRequest);
            }
        }
    }

    /**
    * @description Retries failed request
    * @param failedRequest failed Request
    * @return Returns whether the response was successfully handled
    */
    private Boolean retryFailedRequest(SOM_FailedRequest__c failedRequest) {
        // Create request instance and cast it to SOM_AbstractRequest
        SOM_AbstractRequest request = (SOM_AbstractRequest) Type.forName(failedRequest.Name).newInstance();
        // Send request
        HttpResponse result = request.process(failedRequest);
        // Handle Response
        Boolean isResponseHandledSuccessfully = request.handleResponse(result);
        return isResponseHandledSuccessfully;
    }
}