Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/SOM_FailedRequest__c.object-meta.xml
<CustomObject>
    <label>Failed Request</label>
    <nameField>
        <label>Failed Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Failed Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>Stores the request body as JSON.</description>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/IsRetryAttemptLimitReached__c.field-meta.xml
<CustomField>
    <fullName>IsRetryAttemptLimitReached__c</fullName>
    <description>Calculates the result by subtracting the retry count from the retry limit.

While attempt is less than limit, the result will be false and will be retried again. Once it reaches, the result will be true and will be excluded from SOQL.

attempt &lt; limit ? false: true</description>
    <formula>RetryAttemptLimit__c -  RetryAttempts__c = 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retry Attempt Limit Reached</label>
    <type>Checkbox</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/RegenerateData__c.field-meta.xml
<CustomField>
    <fullName>RegenerateData__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the request body will be regenerated. 

(If true, Data field will be noneffective)</description>
    <label>Regenerate Data</label>
    <type>Checkbox</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/RegenerateDataParameter__c.field-meta.xml
<CustomField>
    <fullName>RegenerateDataParameter__c</fullName>
    <description>Stores the parameter for retry data.</description>
    <label>Regenerate Data Parameter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/RetryAttempts__c.field-meta.xml
<CustomField>
    <fullName>RetryAttempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the number of retry attempts.</description>
    <label>Retry Attempts</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_FailedRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the retry object.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT STARTED</fullName>
                <default>true</default>
                <label>NOT STARTED</label>
            </value>
            <value>
                <fullName>IN PROGRESS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/classes/selectors/failedRequest/SOM_FailedRequestSelector.cls
/**
* @description FailedRequest selector class
*/
public with sharing class SOM_FailedRequestSelector implements SOM_IFailedRequestSelector {
    /**
    * @description Selects FailedRequest records based on the avaibility of retry and status
    * @param isRetryAttemptLimitReached is retry attempt limit reached 
    * @param status status of failedRequest
    * @param querySize query limit
    * @return List of FailedRequest
    */
    public List<SOM_FailedRequest__c> selectByAvaibilityOfRetryAndStatus(Boolean isRetryAttemptLimitReached, String status, Integer querySize) {
        return [SELECT 
                    Id,
                    Name,
                    Data__c,
                    RegenerateData__c,
                    RetryAttempts__c,
                    RegenerateDataParameter__c
                FROM SOM_FailedRequest__c 
                WHERE IsRetryAttemptLimitReached__c =: isRetryAttemptLimitReached
                AND Status__c =: status
                WITH SECURITY_ENFORCED
                LIMIT :querySize];
    }
}