Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_BatchConfiguration__mdt/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <defaultValue>100</defaultValue>
    <description>Size of the batch.</description>
    <label>Batch Size</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_BatchConfiguration__mdt/fields/ErrorEmailRecipients__c.field-meta.xml
<CustomField>
    <fullName>ErrorEmailRecipients__c</fullName>
    <description>Recipient list for error emails.</description>
    <inlineHelpText>Separate with comma.</inlineHelpText>
    <label>Error Email Recipients</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_BatchConfiguration__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if the configuration is active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_BatchConfiguration__mdt/fields/QuerySize__c.field-meta.xml
<CustomField>
    <fullName>QuerySize__c</fullName>
    <defaultValue>200</defaultValue>
    <description>Size of the query.</description>
    <label>Query Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_BatchConfiguration__mdt/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>3</defaultValue>
    <description>The count of retry mechanism for failed records.</description>
    <label>Retry Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_BatchConfiguration__mdt/fields/SendErrorEmail__c.field-meta.xml
<CustomField>
    <fullName>SendErrorEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, sends error email to Error Email Recipients</description>
    <label>Send Error Email</label>
    <type>Checkbox</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_BatchConfiguration__mdt/fields/SendSuccessEmail__c.field-meta.xml
<CustomField>
    <fullName>SendSuccessEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, send success email.</description>
    <label>Send Success Email</label>
    <type>Checkbox</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/objects/SOM_BatchConfiguration__mdt/fields/SuccessEmailRecipients__c.field-meta.xml
<CustomField>
    <fullName>SuccessEmailRecipients__c</fullName>
    <description>Recipient list for success emails.</description>
    <inlineHelpText>Separate with comma.</inlineHelpText>
    <label>Success Email Recipients</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Design-Architecture-Advisory-Board-develop/salesforce-order-management-template/force-app/main/default/classes/batchJobs/SOM_BatchJobHandler.cls
/**
* @description Handler class for batches and 
*   scheduled jobs
*/
public with sharing virtual class SOM_BatchJobHandler {
    private SOM_BatchConfiguration__mdt configuration;
    @testVisible
    protected Integer batchSize;
    @testVisible
    protected Boolean isActive;
    @testVisible
    protected Integer querySize;
    @testVisible
    protected Integer retryCount;
    @testVisible
    protected Boolean sendErrorEmail;
    @testVisible
    protected String errorEmailRecipients;
    @testVisible
    protected Boolean sendSuccessEmail;
    @testVisible
    protected String successEmailRecipients;

    /**
    * @description Gets configuration by the name
    * @param configurationName The name of the configuration
    */
    public SOM_BatchJobHandler(String configurationName) {
        this.configuration = Test.isRunningTest() 
            ? SOM_TestDataFactory.createSOMBatchConfigurationRecord()
            : SOM_BatchConfiguration__mdt.getInstance(configurationName);
            
        if (configuration == null) {
            throw new BatchJobHandlerException('Missing configuration: ' + configurationName);
        }     
        
        this.isActive = configuration.IsActive__c;
        this.batchSize = Integer.valueOf(configuration.BatchSize__c);
        this.querySize = Integer.valueOf(configuration.QuerySize__c);
        this.retryCount = Integer.valueOf(configuration.RetryCount__c);
        this.sendErrorEmail = Boolean.valueOf(configuration.SendErrorEmail__c);
        this.errorEmailRecipients = configuration.ErrorEmailRecipients__c;
        this.sendSuccessEmail = Boolean.valueOf(configuration.SendSuccessEmail__c);
        this.successEmailRecipients = configuration.SuccessEmailRecipients__c;
    }

    /**
    * @description Send success email if enabled
    * @return List of Messaging.SendEmailResult
    */
    @testVisible
    protected List<Messaging.SendEmailResult> sendSuccessEmail() {
        return configuration.SendSuccessEmail__c 
            ? SOM_EmailUtil.sendEmail(configuration.SuccessEmailRecipients__c.split(','), SOM_Constants.SUCCESS, SOM_Constants.SUCCESS, false)
            : new List<Messaging.SendEmailResult>();
    }

    /**
    * @description Send error email if enabled
    * @param errorMessage The error message
    * @return List of Messaging.SendEmailResult
    */
    @testVisible
    protected List<Messaging.SendEmailResult> sendErrorEmail(String errorMessage) {
        return configuration.SendErrorEmail__c
            ? SOM_EmailUtil.sendEmail(configuration.ErrorEmailRecipients__c.split(','), SOM_Constants.ERROR, errorMessage, false)
            : new List<Messaging.SendEmailResult>();
    }

    /**
    * @description Batch job handler exception 
    */
    public class BatchJobHandlerException extends Exception { }
}